name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/
        
    - name: Clean up extraheader
      run: |
        git config --global --unset-all http.https://github.com/.extraheader
        git submodule foreach --recursive git config --local --unset-all http.https://github.com/.extraheader
